resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/21.yaml

# User packages to be built.
packages:
- '.'


extra-deps:
- github: DSLsofMath/Hatlab
  commit: 8a842849a7f492c430afb2d648d8ff0e95628d35


flags: {}

